// Code generated by entc, DO NOT EDIT.

package faculty

const (
	// Label holds the string label denoting the faculty type in the database.
	Label = "faculty"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFname holds the string denoting the fname field in the database.
	FieldFname = "fname"

	// EdgeBranchs holds the string denoting the branchs edge name in mutations.
	EdgeBranchs = "branchs"
	// EdgeUserInformations holds the string denoting the user_informations edge name in mutations.
	EdgeUserInformations = "user_informations"

	// Table holds the table name of the faculty in the database.
	Table = "faculties"
	// BranchsTable is the table the holds the branchs relation/edge.
	BranchsTable = "branches"
	// BranchsInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchsInverseTable = "branches"
	// BranchsColumn is the table column denoting the branchs relation/edge.
	BranchsColumn = "faculty_id"
	// UserInformationsTable is the table the holds the user_informations relation/edge.
	UserInformationsTable = "users"
	// UserInformationsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInformationsInverseTable = "users"
	// UserInformationsColumn is the table column denoting the user_informations relation/edge.
	UserInformationsColumn = "faculty_id"
)

// Columns holds all SQL columns for faculty fields.
var Columns = []string{
	FieldID,
	FieldFname,
}
