// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/moominzie/user-record/ent/migrate"

	"github.com/moominzie/user-record/ent/branch"
	"github.com/moominzie/user-record/ent/building"
	"github.com/moominzie/user-record/ent/employee"
	"github.com/moominzie/user-record/ent/faculty"
	"github.com/moominzie/user-record/ent/repairinvoice"
	"github.com/moominzie/user-record/ent/returninvoice"
	"github.com/moominzie/user-record/ent/room"
	"github.com/moominzie/user-record/ent/statust"
	"github.com/moominzie/user-record/ent/user"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Branch is the client for interacting with the Branch builders.
	Branch *BranchClient
	// Building is the client for interacting with the Building builders.
	Building *BuildingClient
	// Employee is the client for interacting with the Employee builders.
	Employee *EmployeeClient
	// Faculty is the client for interacting with the Faculty builders.
	Faculty *FacultyClient
	// Repairinvoice is the client for interacting with the Repairinvoice builders.
	Repairinvoice *RepairinvoiceClient
	// Returninvoice is the client for interacting with the Returninvoice builders.
	Returninvoice *ReturninvoiceClient
	// Room is the client for interacting with the Room builders.
	Room *RoomClient
	// Statust is the client for interacting with the Statust builders.
	Statust *StatustClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Branch = NewBranchClient(c.config)
	c.Building = NewBuildingClient(c.config)
	c.Employee = NewEmployeeClient(c.config)
	c.Faculty = NewFacultyClient(c.config)
	c.Repairinvoice = NewRepairinvoiceClient(c.config)
	c.Returninvoice = NewReturninvoiceClient(c.config)
	c.Room = NewRoomClient(c.config)
	c.Statust = NewStatustClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Branch:        NewBranchClient(cfg),
		Building:      NewBuildingClient(cfg),
		Employee:      NewEmployeeClient(cfg),
		Faculty:       NewFacultyClient(cfg),
		Repairinvoice: NewRepairinvoiceClient(cfg),
		Returninvoice: NewReturninvoiceClient(cfg),
		Room:          NewRoomClient(cfg),
		Statust:       NewStatustClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:        cfg,
		Branch:        NewBranchClient(cfg),
		Building:      NewBuildingClient(cfg),
		Employee:      NewEmployeeClient(cfg),
		Faculty:       NewFacultyClient(cfg),
		Repairinvoice: NewRepairinvoiceClient(cfg),
		Returninvoice: NewReturninvoiceClient(cfg),
		Room:          NewRoomClient(cfg),
		Statust:       NewStatustClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Branch.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Branch.Use(hooks...)
	c.Building.Use(hooks...)
	c.Employee.Use(hooks...)
	c.Faculty.Use(hooks...)
	c.Repairinvoice.Use(hooks...)
	c.Returninvoice.Use(hooks...)
	c.Room.Use(hooks...)
	c.Statust.Use(hooks...)
	c.User.Use(hooks...)
}

// BranchClient is a client for the Branch schema.
type BranchClient struct {
	config
}

// NewBranchClient returns a client for the Branch from the given config.
func NewBranchClient(c config) *BranchClient {
	return &BranchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `branch.Hooks(f(g(h())))`.
func (c *BranchClient) Use(hooks ...Hook) {
	c.hooks.Branch = append(c.hooks.Branch, hooks...)
}

// Create returns a create builder for Branch.
func (c *BranchClient) Create() *BranchCreate {
	mutation := newBranchMutation(c.config, OpCreate)
	return &BranchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Branch.
func (c *BranchClient) Update() *BranchUpdate {
	mutation := newBranchMutation(c.config, OpUpdate)
	return &BranchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BranchClient) UpdateOne(b *Branch) *BranchUpdateOne {
	mutation := newBranchMutation(c.config, OpUpdateOne, withBranch(b))
	return &BranchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BranchClient) UpdateOneID(id int) *BranchUpdateOne {
	mutation := newBranchMutation(c.config, OpUpdateOne, withBranchID(id))
	return &BranchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Branch.
func (c *BranchClient) Delete() *BranchDelete {
	mutation := newBranchMutation(c.config, OpDelete)
	return &BranchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *BranchClient) DeleteOne(b *Branch) *BranchDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *BranchClient) DeleteOneID(id int) *BranchDeleteOne {
	builder := c.Delete().Where(branch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BranchDeleteOne{builder}
}

// Create returns a query builder for Branch.
func (c *BranchClient) Query() *BranchQuery {
	return &BranchQuery{config: c.config}
}

// Get returns a Branch entity by its id.
func (c *BranchClient) Get(ctx context.Context, id int) (*Branch, error) {
	return c.Query().Where(branch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BranchClient) GetX(ctx context.Context, id int) *Branch {
	b, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return b
}

// QueryFaculty queries the faculty edge of a Branch.
func (c *BranchClient) QueryFaculty(b *Branch) *FacultyQuery {
	query := &FacultyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(branch.Table, branch.FieldID, id),
			sqlgraph.To(faculty.Table, faculty.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, branch.FacultyTable, branch.FacultyColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserInformations queries the user_informations edge of a Branch.
func (c *BranchClient) QueryUserInformations(b *Branch) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(branch.Table, branch.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, branch.UserInformationsTable, branch.UserInformationsColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BranchClient) Hooks() []Hook {
	return c.hooks.Branch
}

// BuildingClient is a client for the Building schema.
type BuildingClient struct {
	config
}

// NewBuildingClient returns a client for the Building from the given config.
func NewBuildingClient(c config) *BuildingClient {
	return &BuildingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `building.Hooks(f(g(h())))`.
func (c *BuildingClient) Use(hooks ...Hook) {
	c.hooks.Building = append(c.hooks.Building, hooks...)
}

// Create returns a create builder for Building.
func (c *BuildingClient) Create() *BuildingCreate {
	mutation := newBuildingMutation(c.config, OpCreate)
	return &BuildingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Building.
func (c *BuildingClient) Update() *BuildingUpdate {
	mutation := newBuildingMutation(c.config, OpUpdate)
	return &BuildingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BuildingClient) UpdateOne(b *Building) *BuildingUpdateOne {
	mutation := newBuildingMutation(c.config, OpUpdateOne, withBuilding(b))
	return &BuildingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BuildingClient) UpdateOneID(id int) *BuildingUpdateOne {
	mutation := newBuildingMutation(c.config, OpUpdateOne, withBuildingID(id))
	return &BuildingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Building.
func (c *BuildingClient) Delete() *BuildingDelete {
	mutation := newBuildingMutation(c.config, OpDelete)
	return &BuildingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *BuildingClient) DeleteOne(b *Building) *BuildingDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *BuildingClient) DeleteOneID(id int) *BuildingDeleteOne {
	builder := c.Delete().Where(building.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BuildingDeleteOne{builder}
}

// Create returns a query builder for Building.
func (c *BuildingClient) Query() *BuildingQuery {
	return &BuildingQuery{config: c.config}
}

// Get returns a Building entity by its id.
func (c *BuildingClient) Get(ctx context.Context, id int) (*Building, error) {
	return c.Query().Where(building.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BuildingClient) GetX(ctx context.Context, id int) *Building {
	b, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return b
}

// QueryRooms queries the rooms edge of a Building.
func (c *BuildingClient) QueryRooms(b *Building) *RoomQuery {
	query := &RoomQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, id),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, building.RoomsTable, building.RoomsColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserInformations queries the user_informations edge of a Building.
func (c *BuildingClient) QueryUserInformations(b *Building) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(building.Table, building.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, building.UserInformationsTable, building.UserInformationsColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BuildingClient) Hooks() []Hook {
	return c.hooks.Building
}

// EmployeeClient is a client for the Employee schema.
type EmployeeClient struct {
	config
}

// NewEmployeeClient returns a client for the Employee from the given config.
func NewEmployeeClient(c config) *EmployeeClient {
	return &EmployeeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employee.Hooks(f(g(h())))`.
func (c *EmployeeClient) Use(hooks ...Hook) {
	c.hooks.Employee = append(c.hooks.Employee, hooks...)
}

// Create returns a create builder for Employee.
func (c *EmployeeClient) Create() *EmployeeCreate {
	mutation := newEmployeeMutation(c.config, OpCreate)
	return &EmployeeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Employee.
func (c *EmployeeClient) Update() *EmployeeUpdate {
	mutation := newEmployeeMutation(c.config, OpUpdate)
	return &EmployeeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmployeeClient) UpdateOne(e *Employee) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployee(e))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmployeeClient) UpdateOneID(id int) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployeeID(id))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Employee.
func (c *EmployeeClient) Delete() *EmployeeDelete {
	mutation := newEmployeeMutation(c.config, OpDelete)
	return &EmployeeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *EmployeeClient) DeleteOne(e *Employee) *EmployeeDeleteOne {
	return c.DeleteOneID(e.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *EmployeeClient) DeleteOneID(id int) *EmployeeDeleteOne {
	builder := c.Delete().Where(employee.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmployeeDeleteOne{builder}
}

// Create returns a query builder for Employee.
func (c *EmployeeClient) Query() *EmployeeQuery {
	return &EmployeeQuery{config: c.config}
}

// Get returns a Employee entity by its id.
func (c *EmployeeClient) Get(ctx context.Context, id int) (*Employee, error) {
	return c.Query().Where(employee.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmployeeClient) GetX(ctx context.Context, id int) *Employee {
	e, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return e
}

// QueryEmployees queries the employees edge of a Employee.
func (c *EmployeeClient) QueryEmployees(e *Employee) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := e.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(employee.Table, employee.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, employee.EmployeesTable, employee.EmployeesColumn),
		)
		fromV = sqlgraph.Neighbors(e.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmployeeClient) Hooks() []Hook {
	return c.hooks.Employee
}

// FacultyClient is a client for the Faculty schema.
type FacultyClient struct {
	config
}

// NewFacultyClient returns a client for the Faculty from the given config.
func NewFacultyClient(c config) *FacultyClient {
	return &FacultyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `faculty.Hooks(f(g(h())))`.
func (c *FacultyClient) Use(hooks ...Hook) {
	c.hooks.Faculty = append(c.hooks.Faculty, hooks...)
}

// Create returns a create builder for Faculty.
func (c *FacultyClient) Create() *FacultyCreate {
	mutation := newFacultyMutation(c.config, OpCreate)
	return &FacultyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Faculty.
func (c *FacultyClient) Update() *FacultyUpdate {
	mutation := newFacultyMutation(c.config, OpUpdate)
	return &FacultyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FacultyClient) UpdateOne(f *Faculty) *FacultyUpdateOne {
	mutation := newFacultyMutation(c.config, OpUpdateOne, withFaculty(f))
	return &FacultyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FacultyClient) UpdateOneID(id int) *FacultyUpdateOne {
	mutation := newFacultyMutation(c.config, OpUpdateOne, withFacultyID(id))
	return &FacultyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Faculty.
func (c *FacultyClient) Delete() *FacultyDelete {
	mutation := newFacultyMutation(c.config, OpDelete)
	return &FacultyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *FacultyClient) DeleteOne(f *Faculty) *FacultyDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *FacultyClient) DeleteOneID(id int) *FacultyDeleteOne {
	builder := c.Delete().Where(faculty.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FacultyDeleteOne{builder}
}

// Create returns a query builder for Faculty.
func (c *FacultyClient) Query() *FacultyQuery {
	return &FacultyQuery{config: c.config}
}

// Get returns a Faculty entity by its id.
func (c *FacultyClient) Get(ctx context.Context, id int) (*Faculty, error) {
	return c.Query().Where(faculty.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FacultyClient) GetX(ctx context.Context, id int) *Faculty {
	f, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return f
}

// QueryBranchs queries the branchs edge of a Faculty.
func (c *FacultyClient) QueryBranchs(f *Faculty) *BranchQuery {
	query := &BranchQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(faculty.Table, faculty.FieldID, id),
			sqlgraph.To(branch.Table, branch.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, faculty.BranchsTable, faculty.BranchsColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserInformations queries the user_informations edge of a Faculty.
func (c *FacultyClient) QueryUserInformations(f *Faculty) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(faculty.Table, faculty.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, faculty.UserInformationsTable, faculty.UserInformationsColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FacultyClient) Hooks() []Hook {
	return c.hooks.Faculty
}

// RepairinvoiceClient is a client for the Repairinvoice schema.
type RepairinvoiceClient struct {
	config
}

// NewRepairinvoiceClient returns a client for the Repairinvoice from the given config.
func NewRepairinvoiceClient(c config) *RepairinvoiceClient {
	return &RepairinvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repairinvoice.Hooks(f(g(h())))`.
func (c *RepairinvoiceClient) Use(hooks ...Hook) {
	c.hooks.Repairinvoice = append(c.hooks.Repairinvoice, hooks...)
}

// Create returns a create builder for Repairinvoice.
func (c *RepairinvoiceClient) Create() *RepairinvoiceCreate {
	mutation := newRepairinvoiceMutation(c.config, OpCreate)
	return &RepairinvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Repairinvoice.
func (c *RepairinvoiceClient) Update() *RepairinvoiceUpdate {
	mutation := newRepairinvoiceMutation(c.config, OpUpdate)
	return &RepairinvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepairinvoiceClient) UpdateOne(r *Repairinvoice) *RepairinvoiceUpdateOne {
	mutation := newRepairinvoiceMutation(c.config, OpUpdateOne, withRepairinvoice(r))
	return &RepairinvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepairinvoiceClient) UpdateOneID(id int) *RepairinvoiceUpdateOne {
	mutation := newRepairinvoiceMutation(c.config, OpUpdateOne, withRepairinvoiceID(id))
	return &RepairinvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repairinvoice.
func (c *RepairinvoiceClient) Delete() *RepairinvoiceDelete {
	mutation := newRepairinvoiceMutation(c.config, OpDelete)
	return &RepairinvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RepairinvoiceClient) DeleteOne(r *Repairinvoice) *RepairinvoiceDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RepairinvoiceClient) DeleteOneID(id int) *RepairinvoiceDeleteOne {
	builder := c.Delete().Where(repairinvoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepairinvoiceDeleteOne{builder}
}

// Create returns a query builder for Repairinvoice.
func (c *RepairinvoiceClient) Query() *RepairinvoiceQuery {
	return &RepairinvoiceQuery{config: c.config}
}

// Get returns a Repairinvoice entity by its id.
func (c *RepairinvoiceClient) Get(ctx context.Context, id int) (*Repairinvoice, error) {
	return c.Query().Where(repairinvoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepairinvoiceClient) GetX(ctx context.Context, id int) *Repairinvoice {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryRepairinvoices queries the repairinvoices edge of a Repairinvoice.
func (c *RepairinvoiceClient) QueryRepairinvoices(r *Repairinvoice) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repairinvoice.Table, repairinvoice.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, repairinvoice.RepairinvoicesTable, repairinvoice.RepairinvoicesColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepairinvoiceClient) Hooks() []Hook {
	return c.hooks.Repairinvoice
}

// ReturninvoiceClient is a client for the Returninvoice schema.
type ReturninvoiceClient struct {
	config
}

// NewReturninvoiceClient returns a client for the Returninvoice from the given config.
func NewReturninvoiceClient(c config) *ReturninvoiceClient {
	return &ReturninvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `returninvoice.Hooks(f(g(h())))`.
func (c *ReturninvoiceClient) Use(hooks ...Hook) {
	c.hooks.Returninvoice = append(c.hooks.Returninvoice, hooks...)
}

// Create returns a create builder for Returninvoice.
func (c *ReturninvoiceClient) Create() *ReturninvoiceCreate {
	mutation := newReturninvoiceMutation(c.config, OpCreate)
	return &ReturninvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Returninvoice.
func (c *ReturninvoiceClient) Update() *ReturninvoiceUpdate {
	mutation := newReturninvoiceMutation(c.config, OpUpdate)
	return &ReturninvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReturninvoiceClient) UpdateOne(r *Returninvoice) *ReturninvoiceUpdateOne {
	mutation := newReturninvoiceMutation(c.config, OpUpdateOne, withReturninvoice(r))
	return &ReturninvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReturninvoiceClient) UpdateOneID(id int) *ReturninvoiceUpdateOne {
	mutation := newReturninvoiceMutation(c.config, OpUpdateOne, withReturninvoiceID(id))
	return &ReturninvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Returninvoice.
func (c *ReturninvoiceClient) Delete() *ReturninvoiceDelete {
	mutation := newReturninvoiceMutation(c.config, OpDelete)
	return &ReturninvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ReturninvoiceClient) DeleteOne(r *Returninvoice) *ReturninvoiceDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ReturninvoiceClient) DeleteOneID(id int) *ReturninvoiceDeleteOne {
	builder := c.Delete().Where(returninvoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReturninvoiceDeleteOne{builder}
}

// Create returns a query builder for Returninvoice.
func (c *ReturninvoiceClient) Query() *ReturninvoiceQuery {
	return &ReturninvoiceQuery{config: c.config}
}

// Get returns a Returninvoice entity by its id.
func (c *ReturninvoiceClient) Get(ctx context.Context, id int) (*Returninvoice, error) {
	return c.Query().Where(returninvoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReturninvoiceClient) GetX(ctx context.Context, id int) *Returninvoice {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryRepairinvoice queries the Repairinvoice edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryRepairinvoice(r *Returninvoice) *RepairinvoiceQuery {
	query := &RepairinvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(repairinvoice.Table, repairinvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, returninvoice.RepairinvoiceTable, returninvoice.RepairinvoiceColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmployee queries the Employee edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryEmployee(r *Returninvoice) *EmployeeQuery {
	query := &EmployeeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, returninvoice.EmployeeTable, returninvoice.EmployeeColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStatust queries the Statust edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryStatust(r *Returninvoice) *StatustQuery {
	query := &StatustQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(statust.Table, statust.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, returninvoice.StatustTable, returninvoice.StatustColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReturninvoiceClient) Hooks() []Hook {
	return c.hooks.Returninvoice
}

// RoomClient is a client for the Room schema.
type RoomClient struct {
	config
}

// NewRoomClient returns a client for the Room from the given config.
func NewRoomClient(c config) *RoomClient {
	return &RoomClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `room.Hooks(f(g(h())))`.
func (c *RoomClient) Use(hooks ...Hook) {
	c.hooks.Room = append(c.hooks.Room, hooks...)
}

// Create returns a create builder for Room.
func (c *RoomClient) Create() *RoomCreate {
	mutation := newRoomMutation(c.config, OpCreate)
	return &RoomCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Room.
func (c *RoomClient) Update() *RoomUpdate {
	mutation := newRoomMutation(c.config, OpUpdate)
	return &RoomUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoomClient) UpdateOne(r *Room) *RoomUpdateOne {
	mutation := newRoomMutation(c.config, OpUpdateOne, withRoom(r))
	return &RoomUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoomClient) UpdateOneID(id int) *RoomUpdateOne {
	mutation := newRoomMutation(c.config, OpUpdateOne, withRoomID(id))
	return &RoomUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Room.
func (c *RoomClient) Delete() *RoomDelete {
	mutation := newRoomMutation(c.config, OpDelete)
	return &RoomDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RoomClient) DeleteOne(r *Room) *RoomDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RoomClient) DeleteOneID(id int) *RoomDeleteOne {
	builder := c.Delete().Where(room.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoomDeleteOne{builder}
}

// Create returns a query builder for Room.
func (c *RoomClient) Query() *RoomQuery {
	return &RoomQuery{config: c.config}
}

// Get returns a Room entity by its id.
func (c *RoomClient) Get(ctx context.Context, id int) (*Room, error) {
	return c.Query().Where(room.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoomClient) GetX(ctx context.Context, id int) *Room {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryBuilding queries the building edge of a Room.
func (c *RoomClient) QueryBuilding(r *Room) *BuildingQuery {
	query := &BuildingQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(room.Table, room.FieldID, id),
			sqlgraph.To(building.Table, building.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, room.BuildingTable, room.BuildingColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserInformations queries the user_informations edge of a Room.
func (c *RoomClient) QueryUserInformations(r *Room) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(room.Table, room.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, room.UserInformationsTable, room.UserInformationsColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RoomClient) Hooks() []Hook {
	return c.hooks.Room
}

// StatustClient is a client for the Statust schema.
type StatustClient struct {
	config
}

// NewStatustClient returns a client for the Statust from the given config.
func NewStatustClient(c config) *StatustClient {
	return &StatustClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `statust.Hooks(f(g(h())))`.
func (c *StatustClient) Use(hooks ...Hook) {
	c.hooks.Statust = append(c.hooks.Statust, hooks...)
}

// Create returns a create builder for Statust.
func (c *StatustClient) Create() *StatustCreate {
	mutation := newStatustMutation(c.config, OpCreate)
	return &StatustCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Statust.
func (c *StatustClient) Update() *StatustUpdate {
	mutation := newStatustMutation(c.config, OpUpdate)
	return &StatustUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StatustClient) UpdateOne(s *Statust) *StatustUpdateOne {
	mutation := newStatustMutation(c.config, OpUpdateOne, withStatust(s))
	return &StatustUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StatustClient) UpdateOneID(id int) *StatustUpdateOne {
	mutation := newStatustMutation(c.config, OpUpdateOne, withStatustID(id))
	return &StatustUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Statust.
func (c *StatustClient) Delete() *StatustDelete {
	mutation := newStatustMutation(c.config, OpDelete)
	return &StatustDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *StatustClient) DeleteOne(s *Statust) *StatustDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *StatustClient) DeleteOneID(id int) *StatustDeleteOne {
	builder := c.Delete().Where(statust.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StatustDeleteOne{builder}
}

// Create returns a query builder for Statust.
func (c *StatustClient) Query() *StatustQuery {
	return &StatustQuery{config: c.config}
}

// Get returns a Statust entity by its id.
func (c *StatustClient) Get(ctx context.Context, id int) (*Statust, error) {
	return c.Query().Where(statust.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StatustClient) GetX(ctx context.Context, id int) *Statust {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QueryStatusts queries the statusts edge of a Statust.
func (c *StatustClient) QueryStatusts(s *Statust) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(statust.Table, statust.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, statust.StatustsTable, statust.StatustsColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StatustClient) Hooks() []Hook {
	return c.hooks.Statust
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Create returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{config: c.config}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	u, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return u
}

// QueryFaculty queries the faculty edge of a User.
func (c *UserClient) QueryFaculty(u *User) *FacultyQuery {
	query := &FacultyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(faculty.Table, faculty.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.FacultyTable, user.FacultyColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBranch queries the branch edge of a User.
func (c *UserClient) QueryBranch(u *User) *BranchQuery {
	query := &BranchQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(branch.Table, branch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.BranchTable, user.BranchColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBuilding queries the building edge of a User.
func (c *UserClient) QueryBuilding(u *User) *BuildingQuery {
	query := &BuildingQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(building.Table, building.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.BuildingTable, user.BuildingColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRoom queries the room edge of a User.
func (c *UserClient) QueryRoom(u *User) *RoomQuery {
	query := &RoomQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.RoomTable, user.RoomColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
