// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/moominzie/user-record/ent/predicate"
	"github.com/moominzie/user-record/ent/repairinvoice"
	"github.com/moominzie/user-record/ent/statusr"
)

// StatusRQuery is the builder for querying StatusR entities.
type StatusRQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.StatusR
	// eager-loading edges.
	withRepairInformation *RepairInvoiceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (sr *StatusRQuery) Where(ps ...predicate.StatusR) *StatusRQuery {
	sr.predicates = append(sr.predicates, ps...)
	return sr
}

// Limit adds a limit step to the query.
func (sr *StatusRQuery) Limit(limit int) *StatusRQuery {
	sr.limit = &limit
	return sr
}

// Offset adds an offset step to the query.
func (sr *StatusRQuery) Offset(offset int) *StatusRQuery {
	sr.offset = &offset
	return sr
}

// Order adds an order step to the query.
func (sr *StatusRQuery) Order(o ...OrderFunc) *StatusRQuery {
	sr.order = append(sr.order, o...)
	return sr
}

// QueryRepairInformation chains the current query on the repair_information edge.
func (sr *StatusRQuery) QueryRepairInformation() *RepairInvoiceQuery {
	query := &RepairInvoiceQuery{config: sr.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sr.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(statusr.Table, statusr.FieldID, sr.sqlQuery()),
			sqlgraph.To(repairinvoice.Table, repairinvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, statusr.RepairInformationTable, statusr.RepairInformationColumn),
		)
		fromU = sqlgraph.SetNeighbors(sr.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StatusR entity in the query. Returns *NotFoundError when no statusr was found.
func (sr *StatusRQuery) First(ctx context.Context) (*StatusR, error) {
	sSlice, err := sr.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(sSlice) == 0 {
		return nil, &NotFoundError{statusr.Label}
	}
	return sSlice[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sr *StatusRQuery) FirstX(ctx context.Context) *StatusR {
	s, err := sr.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return s
}

// FirstID returns the first StatusR id in the query. Returns *NotFoundError when no id was found.
func (sr *StatusRQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sr.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{statusr.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (sr *StatusRQuery) FirstXID(ctx context.Context) int {
	id, err := sr.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only StatusR entity in the query, returns an error if not exactly one entity was returned.
func (sr *StatusRQuery) Only(ctx context.Context) (*StatusR, error) {
	sSlice, err := sr.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(sSlice) {
	case 1:
		return sSlice[0], nil
	case 0:
		return nil, &NotFoundError{statusr.Label}
	default:
		return nil, &NotSingularError{statusr.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sr *StatusRQuery) OnlyX(ctx context.Context) *StatusR {
	s, err := sr.Only(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// OnlyID returns the only StatusR id in the query, returns an error if not exactly one id was returned.
func (sr *StatusRQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sr.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = &NotSingularError{statusr.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sr *StatusRQuery) OnlyIDX(ctx context.Context) int {
	id, err := sr.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StatusRs.
func (sr *StatusRQuery) All(ctx context.Context) ([]*StatusR, error) {
	if err := sr.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sr.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sr *StatusRQuery) AllX(ctx context.Context) []*StatusR {
	sSlice, err := sr.All(ctx)
	if err != nil {
		panic(err)
	}
	return sSlice
}

// IDs executes the query and returns a list of StatusR ids.
func (sr *StatusRQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := sr.Select(statusr.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sr *StatusRQuery) IDsX(ctx context.Context) []int {
	ids, err := sr.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sr *StatusRQuery) Count(ctx context.Context) (int, error) {
	if err := sr.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sr.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sr *StatusRQuery) CountX(ctx context.Context) int {
	count, err := sr.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sr *StatusRQuery) Exist(ctx context.Context) (bool, error) {
	if err := sr.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sr.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sr *StatusRQuery) ExistX(ctx context.Context) bool {
	exist, err := sr.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sr *StatusRQuery) Clone() *StatusRQuery {
	return &StatusRQuery{
		config:     sr.config,
		limit:      sr.limit,
		offset:     sr.offset,
		order:      append([]OrderFunc{}, sr.order...),
		unique:     append([]string{}, sr.unique...),
		predicates: append([]predicate.StatusR{}, sr.predicates...),
		// clone intermediate query.
		sql:  sr.sql.Clone(),
		path: sr.path,
	}
}

//  WithRepairInformation tells the query-builder to eager-loads the nodes that are connected to
// the "repair_information" edge. The optional arguments used to configure the query builder of the edge.
func (sr *StatusRQuery) WithRepairInformation(opts ...func(*RepairInvoiceQuery)) *StatusRQuery {
	query := &RepairInvoiceQuery{config: sr.config}
	for _, opt := range opts {
		opt(query)
	}
	sr.withRepairInformation = query
	return sr
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sname string `json:"Sname,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StatusR.Query().
//		GroupBy(statusr.FieldSname).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sr *StatusRQuery) GroupBy(field string, fields ...string) *StatusRGroupBy {
	group := &StatusRGroupBy{config: sr.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sr.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sr.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Sname string `json:"Sname,omitempty"`
//	}
//
//	client.StatusR.Query().
//		Select(statusr.FieldSname).
//		Scan(ctx, &v)
//
func (sr *StatusRQuery) Select(field string, fields ...string) *StatusRSelect {
	selector := &StatusRSelect{config: sr.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sr.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sr.sqlQuery(), nil
	}
	return selector
}

func (sr *StatusRQuery) prepareQuery(ctx context.Context) error {
	if sr.path != nil {
		prev, err := sr.path(ctx)
		if err != nil {
			return err
		}
		sr.sql = prev
	}
	return nil
}

func (sr *StatusRQuery) sqlAll(ctx context.Context) ([]*StatusR, error) {
	var (
		nodes       = []*StatusR{}
		_spec       = sr.querySpec()
		loadedTypes = [1]bool{
			sr.withRepairInformation != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &StatusR{config: sr.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, sr.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := sr.withRepairInformation; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*StatusR)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.RepairInvoice(func(s *sql.Selector) {
			s.Where(sql.InValues(statusr.RepairInformationColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.statusr_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "statusr_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "statusr_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.RepairInformation = append(node.Edges.RepairInformation, n)
		}
	}

	return nodes, nil
}

func (sr *StatusRQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sr.querySpec()
	return sqlgraph.CountNodes(ctx, sr.driver, _spec)
}

func (sr *StatusRQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sr.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (sr *StatusRQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   statusr.Table,
			Columns: statusr.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statusr.FieldID,
			},
		},
		From:   sr.sql,
		Unique: true,
	}
	if ps := sr.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sr.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sr.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sr.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sr *StatusRQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(sr.driver.Dialect())
	t1 := builder.Table(statusr.Table)
	selector := builder.Select(t1.Columns(statusr.Columns...)...).From(t1)
	if sr.sql != nil {
		selector = sr.sql
		selector.Select(selector.Columns(statusr.Columns...)...)
	}
	for _, p := range sr.predicates {
		p(selector)
	}
	for _, p := range sr.order {
		p(selector)
	}
	if offset := sr.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sr.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StatusRGroupBy is the builder for group-by StatusR entities.
type StatusRGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srb *StatusRGroupBy) Aggregate(fns ...AggregateFunc) *StatusRGroupBy {
	srb.fns = append(srb.fns, fns...)
	return srb
}

// Scan applies the group-by query and scan the result into the given value.
func (srb *StatusRGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := srb.path(ctx)
	if err != nil {
		return err
	}
	srb.sql = query
	return srb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (srb *StatusRGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := srb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(srb.fields) > 1 {
		return nil, errors.New("ent: StatusRGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := srb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (srb *StatusRGroupBy) StringsX(ctx context.Context) []string {
	v, err := srb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = srb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (srb *StatusRGroupBy) StringX(ctx context.Context) string {
	v, err := srb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(srb.fields) > 1 {
		return nil, errors.New("ent: StatusRGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := srb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (srb *StatusRGroupBy) IntsX(ctx context.Context) []int {
	v, err := srb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = srb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (srb *StatusRGroupBy) IntX(ctx context.Context) int {
	v, err := srb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(srb.fields) > 1 {
		return nil, errors.New("ent: StatusRGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := srb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (srb *StatusRGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := srb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = srb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (srb *StatusRGroupBy) Float64X(ctx context.Context) float64 {
	v, err := srb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(srb.fields) > 1 {
		return nil, errors.New("ent: StatusRGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := srb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (srb *StatusRGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := srb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (srb *StatusRGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = srb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (srb *StatusRGroupBy) BoolX(ctx context.Context) bool {
	v, err := srb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (srb *StatusRGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := srb.sqlQuery().Query()
	if err := srb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (srb *StatusRGroupBy) sqlQuery() *sql.Selector {
	selector := srb.sql
	columns := make([]string, 0, len(srb.fields)+len(srb.fns))
	columns = append(columns, srb.fields...)
	for _, fn := range srb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(srb.fields...)
}

// StatusRSelect is the builder for select fields of StatusR entities.
type StatusRSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (sr *StatusRSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := sr.path(ctx)
	if err != nil {
		return err
	}
	sr.sql = query
	return sr.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sr *StatusRSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sr.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sr.fields) > 1 {
		return nil, errors.New("ent: StatusRSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sr.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sr *StatusRSelect) StringsX(ctx context.Context) []string {
	v, err := sr.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sr.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sr *StatusRSelect) StringX(ctx context.Context) string {
	v, err := sr.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sr.fields) > 1 {
		return nil, errors.New("ent: StatusRSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sr.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sr *StatusRSelect) IntsX(ctx context.Context) []int {
	v, err := sr.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sr.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sr *StatusRSelect) IntX(ctx context.Context) int {
	v, err := sr.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sr.fields) > 1 {
		return nil, errors.New("ent: StatusRSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sr.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sr *StatusRSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sr.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sr.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sr *StatusRSelect) Float64X(ctx context.Context) float64 {
	v, err := sr.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sr.fields) > 1 {
		return nil, errors.New("ent: StatusRSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sr.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sr *StatusRSelect) BoolsX(ctx context.Context) []bool {
	v, err := sr.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (sr *StatusRSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sr.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{statusr.Label}
	default:
		err = fmt.Errorf("ent: StatusRSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sr *StatusRSelect) BoolX(ctx context.Context) bool {
	v, err := sr.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sr *StatusRSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sr.sqlQuery().Query()
	if err := sr.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sr *StatusRSelect) sqlQuery() sql.Querier {
	selector := sr.sql
	selector.Select(selector.Columns(sr.fields...)...)
	return selector
}
