// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/moominzie/user-record/ent/repairinvoice"
	"github.com/moominzie/user-record/ent/statusr"
)

// StatusRCreate is the builder for creating a StatusR entity.
type StatusRCreate struct {
	config
	mutation *StatusRMutation
	hooks    []Hook
}

// SetSname sets the Sname field.
func (sr *StatusRCreate) SetSname(s string) *StatusRCreate {
	sr.mutation.SetSname(s)
	return sr
}

// AddRepairInformationIDs adds the repair_information edge to RepairInvoice by ids.
func (sr *StatusRCreate) AddRepairInformationIDs(ids ...int) *StatusRCreate {
	sr.mutation.AddRepairInformationIDs(ids...)
	return sr
}

// AddRepairInformation adds the repair_information edges to RepairInvoice.
func (sr *StatusRCreate) AddRepairInformation(r ...*RepairInvoice) *StatusRCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sr.AddRepairInformationIDs(ids...)
}

// Mutation returns the StatusRMutation object of the builder.
func (sr *StatusRCreate) Mutation() *StatusRMutation {
	return sr.mutation
}

// Save creates the StatusR in the database.
func (sr *StatusRCreate) Save(ctx context.Context) (*StatusR, error) {
	if _, ok := sr.mutation.Sname(); !ok {
		return nil, &ValidationError{Name: "Sname", err: errors.New("ent: missing required field \"Sname\"")}
	}
	var (
		err  error
		node *StatusR
	)
	if len(sr.hooks) == 0 {
		node, err = sr.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusRMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sr.mutation = mutation
			node, err = sr.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sr.hooks) - 1; i >= 0; i-- {
			mut = sr.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sr.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sr *StatusRCreate) SaveX(ctx context.Context) *StatusR {
	v, err := sr.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sr *StatusRCreate) sqlSave(ctx context.Context) (*StatusR, error) {
	s, _spec := sr.createSpec()
	if err := sqlgraph.CreateNode(ctx, sr.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sr *StatusRCreate) createSpec() (*StatusR, *sqlgraph.CreateSpec) {
	var (
		s     = &StatusR{config: sr.config}
		_spec = &sqlgraph.CreateSpec{
			Table: statusr.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statusr.FieldID,
			},
		}
	)
	if value, ok := sr.mutation.Sname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statusr.FieldSname,
		})
		s.Sname = value
	}
	if nodes := sr.mutation.RepairInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusr.RepairInformationTable,
			Columns: []string{statusr.RepairInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
