// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/moominzie/user-record/ent/symptom"
)

// Symptom is the model entity for the Symptom schema.
type Symptom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Syname holds the value of the "Syname" field.
	Syname string `json:"Syname,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SymptomQuery when eager-loading is set.
	Edges SymptomEdges `json:"edges"`
}

// SymptomEdges holds the relations/edges for other nodes in the graph.
type SymptomEdges struct {
	// RepairInformation holds the value of the repair_information edge.
	RepairInformation []*RepairInvoice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RepairInformationOrErr returns the RepairInformation value or an error if the edge
// was not loaded in eager-loading.
func (e SymptomEdges) RepairInformationOrErr() ([]*RepairInvoice, error) {
	if e.loadedTypes[0] {
		return e.RepairInformation, nil
	}
	return nil, &NotLoadedError{edge: "repair_information"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Symptom) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Syname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Symptom fields.
func (s *Symptom) assignValues(values ...interface{}) error {
	if m, n := len(values), len(symptom.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Syname", values[0])
	} else if value.Valid {
		s.Syname = value.String
	}
	return nil
}

// QueryRepairInformation queries the repair_information edge of the Symptom.
func (s *Symptom) QueryRepairInformation() *RepairInvoiceQuery {
	return (&SymptomClient{config: s.config}).QueryRepairInformation(s)
}

// Update returns a builder for updating this Symptom.
// Note that, you need to call Symptom.Unwrap() before calling this method, if this Symptom
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Symptom) Update() *SymptomUpdateOne {
	return (&SymptomClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Symptom) Unwrap() *Symptom {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Symptom is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Symptom) String() string {
	var builder strings.Builder
	builder.WriteString("Symptom(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Syname=")
	builder.WriteString(s.Syname)
	builder.WriteByte(')')
	return builder.String()
}

// Symptoms is a parsable slice of Symptom.
type Symptoms []*Symptom

func (s Symptoms) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
