// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/moominzie/user-record/ent/predicate"
	"github.com/moominzie/user-record/ent/repairinvoice"
	"github.com/moominzie/user-record/ent/symptom"
)

// SymptomUpdate is the builder for updating Symptom entities.
type SymptomUpdate struct {
	config
	hooks      []Hook
	mutation   *SymptomMutation
	predicates []predicate.Symptom
}

// Where adds a new predicate for the builder.
func (su *SymptomUpdate) Where(ps ...predicate.Symptom) *SymptomUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetSyname sets the Syname field.
func (su *SymptomUpdate) SetSyname(s string) *SymptomUpdate {
	su.mutation.SetSyname(s)
	return su
}

// AddRepairInformationIDs adds the repair_information edge to RepairInvoice by ids.
func (su *SymptomUpdate) AddRepairInformationIDs(ids ...int) *SymptomUpdate {
	su.mutation.AddRepairInformationIDs(ids...)
	return su
}

// AddRepairInformation adds the repair_information edges to RepairInvoice.
func (su *SymptomUpdate) AddRepairInformation(r ...*RepairInvoice) *SymptomUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddRepairInformationIDs(ids...)
}

// Mutation returns the SymptomMutation object of the builder.
func (su *SymptomUpdate) Mutation() *SymptomMutation {
	return su.mutation
}

// RemoveRepairInformationIDs removes the repair_information edge to RepairInvoice by ids.
func (su *SymptomUpdate) RemoveRepairInformationIDs(ids ...int) *SymptomUpdate {
	su.mutation.RemoveRepairInformationIDs(ids...)
	return su
}

// RemoveRepairInformation removes repair_information edges to RepairInvoice.
func (su *SymptomUpdate) RemoveRepairInformation(r ...*RepairInvoice) *SymptomUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveRepairInformationIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SymptomUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SymptomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SymptomUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SymptomUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SymptomUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SymptomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   symptom.Table,
			Columns: symptom.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: symptom.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Syname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: symptom.FieldSyname,
		})
	}
	if nodes := su.mutation.RemovedRepairInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   symptom.RepairInformationTable,
			Columns: []string{symptom.RepairInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RepairInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   symptom.RepairInformationTable,
			Columns: []string{symptom.RepairInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{symptom.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SymptomUpdateOne is the builder for updating a single Symptom entity.
type SymptomUpdateOne struct {
	config
	hooks    []Hook
	mutation *SymptomMutation
}

// SetSyname sets the Syname field.
func (suo *SymptomUpdateOne) SetSyname(s string) *SymptomUpdateOne {
	suo.mutation.SetSyname(s)
	return suo
}

// AddRepairInformationIDs adds the repair_information edge to RepairInvoice by ids.
func (suo *SymptomUpdateOne) AddRepairInformationIDs(ids ...int) *SymptomUpdateOne {
	suo.mutation.AddRepairInformationIDs(ids...)
	return suo
}

// AddRepairInformation adds the repair_information edges to RepairInvoice.
func (suo *SymptomUpdateOne) AddRepairInformation(r ...*RepairInvoice) *SymptomUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddRepairInformationIDs(ids...)
}

// Mutation returns the SymptomMutation object of the builder.
func (suo *SymptomUpdateOne) Mutation() *SymptomMutation {
	return suo.mutation
}

// RemoveRepairInformationIDs removes the repair_information edge to RepairInvoice by ids.
func (suo *SymptomUpdateOne) RemoveRepairInformationIDs(ids ...int) *SymptomUpdateOne {
	suo.mutation.RemoveRepairInformationIDs(ids...)
	return suo
}

// RemoveRepairInformation removes repair_information edges to RepairInvoice.
func (suo *SymptomUpdateOne) RemoveRepairInformation(r ...*RepairInvoice) *SymptomUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveRepairInformationIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *SymptomUpdateOne) Save(ctx context.Context) (*Symptom, error) {

	var (
		err  error
		node *Symptom
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SymptomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SymptomUpdateOne) SaveX(ctx context.Context) *Symptom {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SymptomUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SymptomUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SymptomUpdateOne) sqlSave(ctx context.Context) (s *Symptom, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   symptom.Table,
			Columns: symptom.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: symptom.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Symptom.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Syname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: symptom.FieldSyname,
		})
	}
	if nodes := suo.mutation.RemovedRepairInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   symptom.RepairInformationTable,
			Columns: []string{symptom.RepairInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RepairInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   symptom.RepairInformationTable,
			Columns: []string{symptom.RepairInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Symptom{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{symptom.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
