// Code generated by entc, DO NOT EDIT.

package device

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDname holds the string denoting the dname field in the database.
	FieldDname = "dname"

	// EdgeRepairInformation holds the string denoting the repair_information edge name in mutations.
	EdgeRepairInformation = "repair_information"

	// Table holds the table name of the device in the database.
	Table = "devices"
	// RepairInformationTable is the table the holds the repair_information relation/edge.
	RepairInformationTable = "repair_invoices"
	// RepairInformationInverseTable is the table name for the RepairInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	RepairInformationInverseTable = "repair_invoices"
	// RepairInformationColumn is the table column denoting the repair_information relation/edge.
	RepairInformationColumn = "device_id"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldDname,
}
