// Code generated by entc, DO NOT EDIT.

package symptom

const (
	// Label holds the string label denoting the symptom type in the database.
	Label = "symptom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSyname holds the string denoting the syname field in the database.
	FieldSyname = "syname"

	// EdgeRepairInformation holds the string denoting the repair_information edge name in mutations.
	EdgeRepairInformation = "repair_information"

	// Table holds the table name of the symptom in the database.
	Table = "symptoms"
	// RepairInformationTable is the table the holds the repair_information relation/edge.
	RepairInformationTable = "repair_invoices"
	// RepairInformationInverseTable is the table name for the RepairInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	RepairInformationInverseTable = "repair_invoices"
	// RepairInformationColumn is the table column denoting the repair_information relation/edge.
	RepairInformationColumn = "symptom_id"
)

// Columns holds all SQL columns for symptom fields.
var Columns = []string{
	FieldID,
	FieldSyname,
}
