// Code generated by entc, DO NOT EDIT.

package partorder

const (
	// Label holds the string label denoting the partorder type in the database.
	Label = "partorder"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeRepairinvoice holds the string denoting the repairinvoice edge name in mutations.
	EdgeRepairinvoice = "repairinvoice"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgePart holds the string denoting the part edge name in mutations.
	EdgePart = "part"

	// Table holds the table name of the partorder in the database.
	Table = "partorders"
	// RepairinvoiceTable is the table the holds the repairinvoice relation/edge.
	RepairinvoiceTable = "partorders"
	// RepairinvoiceInverseTable is the table name for the RepairInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	RepairinvoiceInverseTable = "repair_invoices"
	// RepairinvoiceColumn is the table column denoting the repairinvoice relation/edge.
	RepairinvoiceColumn = "reparinvoice_id"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "partorders"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_id"
	// PartTable is the table the holds the part relation/edge.
	PartTable = "partorders"
	// PartInverseTable is the table name for the Part entity.
	// It exists in this package in order to avoid circular dependency with the "part" package.
	PartInverseTable = "parts"
	// PartColumn is the table column denoting the part relation/edge.
	PartColumn = "part_id"
)

// Columns holds all SQL columns for partorder fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Partorder type.
var ForeignKeys = []string{
	"employee_id",
	"part_id",
	"reparinvoice_id",
}
