// Code generated by entc, DO NOT EDIT.

package part

const (
	// Label holds the string label denoting the part type in the database.
	Label = "part"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPname holds the string denoting the pname field in the database.
	FieldPname = "pname"

	// EdgePartInformations holds the string denoting the part_informations edge name in mutations.
	EdgePartInformations = "part_informations"

	// Table holds the table name of the part in the database.
	Table = "parts"
	// PartInformationsTable is the table the holds the part_informations relation/edge.
	PartInformationsTable = "partorders"
	// PartInformationsInverseTable is the table name for the Partorder entity.
	// It exists in this package in order to avoid circular dependency with the "partorder" package.
	PartInformationsInverseTable = "partorders"
	// PartInformationsColumn is the table column denoting the part_informations relation/edge.
	PartInformationsColumn = "part_id"
)

// Columns holds all SQL columns for part fields.
var Columns = []string{
	FieldID,
	FieldPname,
}
