/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPartorder
 */
export interface ControllersPartorder {
    /**
     * 
     * @type {number}
     * @memberof ControllersPartorder
     */
    employee?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPartorder
     */
    part?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPartorder
     */
    repairinvoice?: number;
}

export function ControllersPartorderFromJSON(json: any): ControllersPartorder {
    return ControllersPartorderFromJSONTyped(json, false);
}

export function ControllersPartorderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPartorder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employee': !exists(json, 'employee') ? undefined : json['employee'],
        'part': !exists(json, 'part') ? undefined : json['part'],
        'repairinvoice': !exists(json, 'repairinvoice') ? undefined : json['repairinvoice'],
    };
}

export function ControllersPartorderToJSON(value?: ControllersPartorder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employee': value.employee,
        'part': value.part,
        'repairinvoice': value.repairinvoice,
    };
}


