/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRepairInvoice,
    EntRepairInvoiceFromJSON,
    EntRepairInvoiceFromJSONTyped,
    EntRepairInvoiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDeviceEdges
 */
export interface EntDeviceEdges {
    /**
     * RepairInformation holds the value of the repair_information edge.
     * @type {Array<EntRepairInvoice>}
     * @memberof EntDeviceEdges
     */
    repairInformation?: Array<EntRepairInvoice>;
}

export function EntDeviceEdgesFromJSON(json: any): EntDeviceEdges {
    return EntDeviceEdgesFromJSONTyped(json, false);
}

export function EntDeviceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDeviceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repairInformation': !exists(json, 'repairInformation') ? undefined : ((json['repairInformation'] as Array<any>).map(EntRepairInvoiceFromJSON)),
    };
}

export function EntDeviceEdgesToJSON(value?: EntDeviceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'repairInformation': value.repairInformation === undefined ? undefined : ((value.repairInformation as Array<any>).map(EntRepairInvoiceToJSON)),
    };
}


