/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntPartorder,
    EntPartorderFromJSON,
    EntPartorderFromJSONTyped,
    EntPartorderToJSON,
    EntReturninvoice,
    EntReturninvoiceFromJSON,
    EntReturninvoiceFromJSONTyped,
    EntReturninvoiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEmployeeEdges
 */
export interface EntEmployeeEdges {
    /**
     * Employeebill holds the value of the employeebill edge.
     * @type {Array<EntBill>}
     * @memberof EntEmployeeEdges
     */
    employeebill?: Array<EntBill>;
    /**
     * Employeepart holds the value of the employeepart edge.
     * @type {Array<EntPartorder>}
     * @memberof EntEmployeeEdges
     */
    employeepart?: Array<EntPartorder>;
    /**
     * Employees holds the value of the employees edge.
     * @type {Array<EntReturninvoice>}
     * @memberof EntEmployeeEdges
     */
    employees?: Array<EntReturninvoice>;
}

export function EntEmployeeEdgesFromJSON(json: any): EntEmployeeEdges {
    return EntEmployeeEdgesFromJSONTyped(json, false);
}

export function EntEmployeeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEmployeeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employeebill': !exists(json, 'employeebill') ? undefined : ((json['employeebill'] as Array<any>).map(EntBillFromJSON)),
        'employeepart': !exists(json, 'employeepart') ? undefined : ((json['employeepart'] as Array<any>).map(EntPartorderFromJSON)),
        'employees': !exists(json, 'employees') ? undefined : ((json['employees'] as Array<any>).map(EntReturninvoiceFromJSON)),
    };
}

export function EntEmployeeEdgesToJSON(value?: EntEmployeeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employeebill': value.employeebill === undefined ? undefined : ((value.employeebill as Array<any>).map(EntBillToJSON)),
        'employeepart': value.employeepart === undefined ? undefined : ((value.employeepart as Array<any>).map(EntPartorderToJSON)),
        'employees': value.employees === undefined ? undefined : ((value.employees as Array<any>).map(EntReturninvoiceToJSON)),
    };
}


