/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPartorder,
    EntPartorderFromJSON,
    EntPartorderFromJSONTyped,
    EntPartorderToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPartEdges
 */
export interface EntPartEdges {
    /**
     * PartInformations holds the value of the part_informations edge.
     * @type {Array<EntPartorder>}
     * @memberof EntPartEdges
     */
    partInformations?: Array<EntPartorder>;
}

export function EntPartEdgesFromJSON(json: any): EntPartEdges {
    return EntPartEdgesFromJSONTyped(json, false);
}

export function EntPartEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPartEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partInformations': !exists(json, 'partInformations') ? undefined : ((json['partInformations'] as Array<any>).map(EntPartorderFromJSON)),
    };
}

export function EntPartEdgesToJSON(value?: EntPartEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partInformations': value.partInformations === undefined ? undefined : ((value.partInformations as Array<any>).map(EntPartorderToJSON)),
    };
}


