/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntDevice,
    EntDeviceFromJSON,
    EntDeviceFromJSONTyped,
    EntDeviceToJSON,
    EntReturninvoice,
    EntReturninvoiceFromJSON,
    EntReturninvoiceFromJSONTyped,
    EntReturninvoiceToJSON,
    EntStatusR,
    EntStatusRFromJSON,
    EntStatusRFromJSONTyped,
    EntStatusRToJSON,
    EntSymptom,
    EntSymptomFromJSON,
    EntSymptomFromJSONTyped,
    EntSymptomToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRepairInvoiceEdges
 */
export interface EntRepairInvoiceEdges {
    /**
     * 
     * @type {EntBill}
     * @memberof EntRepairInvoiceEdges
     */
    bill?: EntBill;
    /**
     * 
     * @type {EntDevice}
     * @memberof EntRepairInvoiceEdges
     */
    device?: EntDevice;
    /**
     * 
     * @type {EntReturninvoice}
     * @memberof EntRepairInvoiceEdges
     */
    returninvoice?: EntReturninvoice;
    /**
     * 
     * @type {EntStatusR}
     * @memberof EntRepairInvoiceEdges
     */
    status?: EntStatusR;
    /**
     * 
     * @type {EntSymptom}
     * @memberof EntRepairInvoiceEdges
     */
    symptom?: EntSymptom;
    /**
     * 
     * @type {EntUser}
     * @memberof EntRepairInvoiceEdges
     */
    user?: EntUser;
}

export function EntRepairInvoiceEdgesFromJSON(json: any): EntRepairInvoiceEdges {
    return EntRepairInvoiceEdgesFromJSONTyped(json, false);
}

export function EntRepairInvoiceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRepairInvoiceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bill': !exists(json, 'Bill') ? undefined : EntBillFromJSON(json['Bill']),
        'device': !exists(json, 'Device') ? undefined : EntDeviceFromJSON(json['Device']),
        'returninvoice': !exists(json, 'Returninvoice') ? undefined : EntReturninvoiceFromJSON(json['Returninvoice']),
        'status': !exists(json, 'Status') ? undefined : EntStatusRFromJSON(json['Status']),
        'symptom': !exists(json, 'Symptom') ? undefined : EntSymptomFromJSON(json['Symptom']),
        'user': !exists(json, 'User') ? undefined : EntUserFromJSON(json['User']),
    };
}

export function EntRepairInvoiceEdgesToJSON(value?: EntRepairInvoiceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bill': EntBillToJSON(value.bill),
        'device': EntDeviceToJSON(value.device),
        'returninvoice': EntReturninvoiceToJSON(value.returninvoice),
        'status': EntStatusRToJSON(value.status),
        'symptom': EntSymptomToJSON(value.symptom),
        'user': EntUserToJSON(value.user),
    };
}


