/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRepairInvoiceEdges,
    EntRepairInvoiceEdgesFromJSON,
    EntRepairInvoiceEdgesFromJSONTyped,
    EntRepairInvoiceEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRepairInvoice
 */
export interface EntRepairInvoice {
    /**
     * Rename holds the value of the "Rename" field.
     * @type {string}
     * @memberof EntRepairInvoice
     */
    rename?: string;
    /**
     * 
     * @type {EntRepairInvoiceEdges}
     * @memberof EntRepairInvoice
     */
    edges?: EntRepairInvoiceEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRepairInvoice
     */
    id?: number;
}

export function EntRepairInvoiceFromJSON(json: any): EntRepairInvoice {
    return EntRepairInvoiceFromJSONTyped(json, false);
}

export function EntRepairInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRepairInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rename': !exists(json, 'Rename') ? undefined : json['Rename'],
        'edges': !exists(json, 'edges') ? undefined : EntRepairInvoiceEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRepairInvoiceToJSON(value?: EntRepairInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Rename': value.rename,
        'edges': EntRepairInvoiceEdgesToJSON(value.edges),
        'id': value.id,
    };
}


