/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRepairInvoice,
    EntRepairInvoiceFromJSON,
    EntRepairInvoiceFromJSONTyped,
    EntRepairInvoiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStatusREdges
 */
export interface EntStatusREdges {
    /**
     * RepairInformation holds the value of the repair_information edge.
     * @type {Array<EntRepairInvoice>}
     * @memberof EntStatusREdges
     */
    repairInformation?: Array<EntRepairInvoice>;
}

export function EntStatusREdgesFromJSON(json: any): EntStatusREdges {
    return EntStatusREdgesFromJSONTyped(json, false);
}

export function EntStatusREdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStatusREdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repairInformation': !exists(json, 'repairInformation') ? undefined : ((json['repairInformation'] as Array<any>).map(EntRepairInvoiceFromJSON)),
    };
}

export function EntStatusREdgesToJSON(value?: EntStatusREdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'repairInformation': value.repairInformation === undefined ? undefined : ((value.repairInformation as Array<any>).map(EntRepairInvoiceToJSON)),
    };
}


