/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSymptomEdges,
    EntSymptomEdgesFromJSON,
    EntSymptomEdgesFromJSONTyped,
    EntSymptomEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSymptom
 */
export interface EntSymptom {
    /**
     * Syname holds the value of the "Syname" field.
     * @type {string}
     * @memberof EntSymptom
     */
    syname?: string;
    /**
     * 
     * @type {EntSymptomEdges}
     * @memberof EntSymptom
     */
    edges?: EntSymptomEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntSymptom
     */
    id?: number;
}

export function EntSymptomFromJSON(json: any): EntSymptom {
    return EntSymptomFromJSONTyped(json, false);
}

export function EntSymptomFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSymptom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'syname': !exists(json, 'Syname') ? undefined : json['Syname'],
        'edges': !exists(json, 'edges') ? undefined : EntSymptomEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntSymptomToJSON(value?: EntSymptom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Syname': value.syname,
        'edges': EntSymptomEdgesToJSON(value.edges),
        'id': value.id,
    };
}


