// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRname holds the string denoting the rname field in the database.
	FieldRname = "rname"

	// EdgeBuilding holds the string denoting the building edge name in mutations.
	EdgeBuilding = "building"
	// EdgeUserInformations holds the string denoting the user_informations edge name in mutations.
	EdgeUserInformations = "user_informations"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// BuildingTable is the table the holds the building relation/edge.
	BuildingTable = "rooms"
	// BuildingInverseTable is the table name for the Building entity.
	// It exists in this package in order to avoid circular dependency with the "building" package.
	BuildingInverseTable = "buildings"
	// BuildingColumn is the table column denoting the building relation/edge.
	BuildingColumn = "building_id"
	// UserInformationsTable is the table the holds the user_informations relation/edge.
	UserInformationsTable = "users"
	// UserInformationsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInformationsInverseTable = "users"
	// UserInformationsColumn is the table column denoting the user_informations relation/edge.
	UserInformationsColumn = "room_id"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldRname,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"building_id",
}
